# Generated by Django 4.0.4 on 2022-05-16 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('username', models.CharField(default='匿名', max_length=100, verbose_name='名前')),
                ('is_active', models.BooleanField(default=True, verbose_name='状況')),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateField(blank=True, null=True, verbose_name='入会日')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutputTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='タグ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='ウメカリメンバー', max_length=30)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='自己紹介')),
                ('target', models.PositiveIntegerField(default=0, verbose_name='目標金額')),
                ('dream', models.ImageField(blank=True, null=True, upload_to='', verbose_name='ビジョンボード')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='質問')),
                ('description', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('tags', models.ManyToManyField(to='base.outputtagmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nippou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.PositiveIntegerField(default=0, verbose_name='販売個数')),
                ('revenue', models.PositiveBigIntegerField(default=0, verbose_name='利益')),
                ('plan', models.TextField(blank=True, default='', null=True, verbose_name='その他')),
                ('date', models.DateField(verbose_name='対象日')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
